# Generated by Django 2.1.1 on 2018-11-23 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20181123_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='upload',
            field=models.FileField(blank=True, upload_to='uploads/'),
        ),
    ]
