# Generated by Django 2.1.1 on 2018-11-23 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='upload_changes',
            field=models.FileField(blank=True, upload_to='uploads/'),
        ),
    ]
