# Generated by Django 2.1.1 on 2018-11-24 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_upload_changes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='upload',
            new_name='current_upload',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='previous_upload',
            field=models.FileField(blank=True, upload_to='uploads/'),
        ),
    ]
